version: '3.8'

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - "50051:50051"

  client:
    build:
      context: .
      dockerfile: client/Dockerfile
    volumes:
      - .:/app
    depends_on:
      - server
    entrypoint: ["python", "client/client.py"]